### ISSUE TITLE
Problème affichage %

### ISSUE THREAD

**Issue by Brouilles** [Exoway/oxem-quest-desktop#1]
Problème d'affichage du % de téléchargement. Voir capture d'écran.
<img width="525" alt="Screenshot 2019-08-08 at 22 52 32" src="https://user-images.githubusercontent.com/1573282/62737123-5c859b80-ba2f-11e9-9844-1ca747b38ac9.png">

**Comment by Milsilver** [comment]
Voir pour ajouter la propriété .toFixed() sur progress.percent

**Comment by Brouilles** [comment]
Je pense plutôt à un `parseInt(progress.percent, 10)`. Mais le toFixed contienne aussi ! 
Pas nécessaire de mettre `bytesPerSecond`, `progress.transferred` et `progress.total` au final dans l'indication. C'est pas spécialement lisible pour un utilisateur lambda. Juste mettre le pourcentage me semble suffisant.

**Comment by Brouilles** [comment]
Fix 03b69be78e544f85e9f7a71103a8db11721047bd
